[package]
name = "example-api"
version = "0.1.0"
authors = ["Simon Chemouil <simon.chemouil@lambdacube.fr>"]
edition = "2018"

[dependencies]
socrates = { path = "../../socrates", version = "0.0.1" }

